title: "Technology Adoption in Latin America (2000-2025): Longitudin"
description: "Longitudinal dataset (2000-2025) on digital technology adoption indicators across 21 Latin American and Iberian countries. Variables: internet penetra"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/technology-adoption-in-latin-america-2000-2025-longitudinal-dataset"
